export const GENERATOR_NAME = 'prisma-generator-go-jet'

export const OUTPUT_HEADER = `//
// Code generated by prisma-generator-go-jet DO NOT EDIT.
// Based on the official go-jet generator output.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//`
